apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd-etcd-stateful
    qihoo-app: etcd
  name: etcd-etcd-stateful
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: etcd-server
    port: 2380
    protocol: TCP
    targetPort: 2380
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd-etcd-stateful
  type: ClusterIP
