apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd-etcd-stateful-client
  name: etcd-etcd-stateful-client
  namespace: default
spec:
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd-etcd-stateful
  type: NodePort
